export const white = '#FFF'
export const black = '#3e4149'
export const gray = '#34374C'
export const lightGray = '#D7DCE4'
export const darkGray = '#2C2E3E'
export const blue = '#1ec0ff'
export const red = '#EE2B47'
export const pink = '#EF466D'