export const white = '#FFF'
export const gray = '#34374C'
export const lightGray = '#bbb'
export const darkGray = '#2C2E3E'
export const blue = '#2b90d9'
export const red = '#EE2B47'
export const pink = '#EF466D'